import { test, expect } from '@playwright/test'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  setWaitForNote,
  enableMic,
  startFakeMic,
  mockMicFromWav,
  startSong,
} from './helpers'

const TAPS_WAV = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures/taps.wav',
)

// Real end-to-end audio test: rather than mocking `detectChord()` at the JS
// level, this feeds an actual synthesized recording of "Taps" into a fake
// microphone (`mockMicFromWav`, fed from e2e/fixtures/taps.wav — generated by
// e2e/fixtures/generate-taps-wav.mjs) and exercises the whole mic pipeline for
// real: the FFT, the chord/onset detector in audio/pitch.ts, and the engine's
// mic-onset debounce in gameEngineCore.ts.
//
// `--mute-audio` (in playwright.config.ts) guarantees none of this is ever
// actually audible on the machine running the test.
//
// taps.wav loops its 15 tones (one per note in Taps's chart, separated by
// silence so each is its own onset) continuously and independently of the
// game's own clock, so there's no way to *time* a press against it. Instead
// this turns on "Wait for correct note": the song holds on each note
// indefinitely rather than timing it out, so whichever matching tone the loop
// plays next always eventually satisfies it, in order, however many loop
// cycles that takes ("-5" the only note that occurs once per 14s loop, so the
// worst case is a small number of loops — hence the long test timeout below).
test('the mic recognizes every note of a real "Taps" performance', async ({
  page,
}) => {
  test.setTimeout(120_000)
  await mockMicFromWav(page, TAPS_WAV, { loop: true })
  await page.goto('/')
  await setWaitForNote(page, true)
  await enableMic(page)
  await startFakeMic(page)
  await startSong(page, 'Taps')

  await expect(
    page.getByRole('heading', { name: 'Song Complete!' }),
  ).toBeVisible({
    timeout: 100_000,
  })
  // Every note was eventually heard and played correctly — none timed out,
  // because "Wait for correct note" never lets that happen — so there should
  // be nothing left in the "wrong instrument" (no note at all detected) or
  // "wrong direction" buckets either: all 15 notes graded as hits.
  await expect(page.locator('.judge--miss strong')).toHaveText('0')
})
