import { test, expect } from '@playwright/test'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  setWaitForNote,
  enableMic,
  startFakeMic,
  mockMicFromWav,
  startSong,
} from './helpers'

const CHORD_PARADE_WAV = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  'fixtures/chord-parade.wav',
)

// Real end-to-end audio test: proves detectChord() (src/audio/pitch.ts)
// actually resolves a real chord — several simultaneous tones — into every
// one of its constituent notes, not just the loudest, the mic equivalent of
// what chord-input.spec.ts proves for a simultaneous keyboard chord. Like
// audio-taps.spec.ts, this feeds an actual synthesized recording into a fake
// microphone (`mockMicFromWav`, fed from e2e/fixtures/chord-parade.wav —
// generated by e2e/fixtures/generate-chord-parade-wav.mjs) and exercises the
// whole mic pipeline for real: the FFT, the multi-pitch chord detector, and
// the engine's mic-onset debounce — across all five of "Chord Parade"'s
// two/three-note chords, not just single notes.
//
// chord-parade.wav loops its beats continuously and independently of the
// game's own clock, so exactly as in audio-taps.spec.ts there's no way to
// *time* a press against it. Instead this turns on "Wait for correct note":
// the song holds on each note/chord indefinitely rather than timing it out,
// so whichever loop cycle eventually plays it correctly always satisfies it.
test('the mic recognizes every note of a real chord, not just one', async ({
  page,
}) => {
  test.setTimeout(120_000)
  await mockMicFromWav(page, CHORD_PARADE_WAV, { loop: true })
  await page.goto('/')
  await setWaitForNote(page, true)
  await enableMic(page)
  await startFakeMic(page)
  await startSong(page, 'Chord Parade')

  await expect(
    page.getByRole('heading', { name: 'Song Complete!' }),
  ).toBeVisible({
    timeout: 100_000,
  })
  // Every note — including every note of every chord — was eventually heard
  // and played correctly, because "Wait for correct note" never lets one
  // time out, so nothing should be left in the miss bucket.
  await expect(page.locator('.judge--miss strong')).toHaveText('0')
})
